name: "hng"
description: "hgn"
title: ""
labels: ""
assignees: ""
issue_body: true
body:
- type: input
  id: test
  attributes:
    label: "d"
    description: "u"
    placeholder: "sda"
    validations:
      required: true
- type: input
  attributes:
    label: "v"
    description: "u"
    placeholder: "u"
    validations:
      required: false
