name: "hng"
description: "hgn"
title: ""
labels: ""
assignees: ""
issue_body: true
body:
- type: input
   attributes:
      label: "v"
      description: "u"
      placeholder: "sda"
      validations:
         required: true
- type: input
   id: f
   attributes:
      label: "f"
      description: "f"
      placeholder: "f"
      validations:
         required: false
