name: "hng"
description: "hgn"
title: ""
labels: ""
assignees: ""
issue_body: true
body:
- type: input
  id: d
  attributes:
    label: "d"
    description: "d"
    placeholder: "d"
  validations:
    required: true
- type: input
  id: test
  attributes:
    label: "v"
    description: "d"
    placeholder: "d"
  validations:
    required: false
